# This workflow will install Python dependencies, produce the sphinx documentation, and publish it to GitHub pages

name: documentation

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

# cancel in-progress run for current workflow when new workflow starts       
# (github.run_id only as fallback, just in case, as per "control workflow concurrency" HOWTO)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-tags: true
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Install dependencies
      run: |
        pip install .[develop]
    - name: Build the docs
      run: |
        sphinx-apidoc -f -o docs/source pisa
        cd docs && make html
      env:
        SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ github.token }}
    - name: Deploy to gh pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        # Destination directory in gh-pages not root but docs/
        destination_dir: docs
        # Don't delete other existing files
        keep_files: true
