# Workflow adapted from https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images#publishing-images-to-github-packages
name: Create and publish a Docker image

# Run on a weekly schedule (Monday morning UTC), when a release or pre-release is published, and when triggered manually
on:
  release:
    types: [published]
  schedule:
    #- cron: '45 0 * * 1'
    - cron: '30 20 * * 1'
      timezone: "UTC"
  workflow_dispatch:

# Three custom environment variables for the workflow: Container registry domain (here: GitHub packages), name for the Docker image, name for the scheduled tag
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SCHED_TAG: weekly

jobs:
  cleanup-old-sched:
    runs-on: ubuntu-latest
    # Only runs cleanup for scheduled builds
    if: github.event_name == 'schedule'
    permissions:
      packages: write
    steps:
      - name: Delete old scheduled images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_NAME }}
          package-type: 'container'
          num-old-versions-to-delete: 0
          delete-only-tags: ${{ env.SCHED_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-image:
    runs-on: ubuntu-latest
    # only run when cleanup is successful or skipped
    if: always() && (needs.cleanup-old-sched.result == 'success' || needs.cleanup-old-sched.result == 'skipped')
    needs: cleanup-old-sched
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-tags: true
      # Uses the `docker/login-action` action to log in to the Container registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Docker Login
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=${{ env.SCHED_TAG }},enable=${{ github.event_name == 'schedule' }}
            type=raw,value=manual-${{ github.run_number }},enable=${{ github.event_name == 'workflow_dispatch' }}
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path.
      # For more information, see [Usage](https://github.com/docker/build-push-action#usage) in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image.
      # For more information, see [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
      #- name: Generate artifact attestation
      #  uses: actions/attest@v4
      #  with:
      #    subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #    subject-digest: ${{ steps.push.outputs.digest }}
      #    push-to-registry: true
